// <auto-generated />
using System;
using BOOKLY.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BOOKLY.Infrastructure.Migrations
{
    [DbContext(typeof(BooklyDbContext))]
    [Migration("20260223211851_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.AppointmentAggregate.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedSecretaryId")
                        .HasColumnType("int")
                        .HasColumnName("assigned_secretary_id");

                    b.Property<string>("ClientNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("client_notes");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date_time");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("internal_notes");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("update_on");

                    b.HasKey("Id");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.AppointmentAggregate.AppointmentFieldValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("appointment_id");

                    b.Property<int>("FieldDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("field_definition_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("appointment_field_values", (string)null);
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.ServiceAggregate.Entities.ServiceSecretary", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    b.Property<int>("SecretaryId")
                        .HasColumnType("int")
                        .HasColumnName("secretary_id");

                    b.HasKey("ServiceId", "SecretaryId");

                    b.HasIndex("SecretaryId")
                        .HasDatabaseName("ix_service_secretaries_secretary_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_service_secretaries_service_id");

                    b.ToTable("service_secretaries", (string)null);
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.ServiceAggregate.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("Mode")
                        .HasColumnType("int")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int")
                        .HasColumnName("service_type_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_services_owner_id");

                    b.HasIndex("ServiceTypeId")
                        .HasDatabaseName("ix_services_service_type_id");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_users_created_at");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_users_is_active");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BOOKLY.Domain.SharedKernel.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("service_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_service_types_name");

                    b.ToTable("service_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Consulta médica",
                            IsActive = true,
                            Name = "Consulta"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sesión de tratamiento",
                            IsActive = true,
                            Name = "Tratamiento"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Consulta de seguimiento",
                            IsActive = true,
                            Name = "Seguimiento"
                        });
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.AppointmentAggregate.Appointment", b =>
                {
                    b.OwnsOne("BOOKLY.Domain.Aggregates.ServiceAggregate.ValueObjects.Duration", "Duration", b1 =>
                        {
                            b1.Property<int>("AppointmentId")
                                .HasColumnType("int");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("duration_minutes");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("appointments");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.OwnsOne("BOOKLY.Domain.Aggregates.AppointmentAggregate.ClientInfo", "Client", b1 =>
                        {
                            b1.Property<int>("AppointmentId")
                                .HasColumnType("int");

                            b1.Property<string>("ClientName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("client_name");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("client_phone");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("appointments");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");

                            b1.OwnsOne("BOOKLY.Domain.SharedKernel.Email", "Email", b2 =>
                                {
                                    b2.Property<int>("ClientInfoAppointmentId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("nvarchar(255)")
                                        .HasColumnName("client_email");

                                    b2.HasKey("ClientInfoAppointmentId");

                                    b2.ToTable("appointments");

                                    b2.WithOwner()
                                        .HasForeignKey("ClientInfoAppointmentId");
                                });

                            b1.Navigation("Email")
                                .IsRequired();
                        });

                    b.Navigation("Client")
                        .IsRequired();

                    b.Navigation("Duration")
                        .IsRequired();
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.AppointmentAggregate.AppointmentFieldValue", b =>
                {
                    b.HasOne("BOOKLY.Domain.Aggregates.AppointmentAggregate.Appointment", null)
                        .WithMany("FieldValues")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.ServiceAggregate.Entities.ServiceSecretary", b =>
                {
                    b.HasOne("BOOKLY.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("SecretaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BOOKLY.Domain.Aggregates.ServiceAggregate.Service", null)
                        .WithMany("ServiceSecretaries")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.ServiceAggregate.Service", b =>
                {
                    b.HasOne("BOOKLY.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BOOKLY.Domain.SharedKernel.ServiceType", null)
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("BOOKLY.Domain.Aggregates.ServiceAggregate.ValueObjects.Duration", "DurationMinutes", b1 =>
                        {
                            b1.Property<int>("ServiceId")
                                .HasColumnType("int");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("duration_minutes");

                            b1.HasKey("ServiceId");

                            b1.ToTable("services");

                            b1.WithOwner()
                                .HasForeignKey("ServiceId");
                        });

                    b.OwnsOne("BOOKLY.Domain.Aggregates.ServiceAggregate.ValueObjects.Slug", "Slug", b1 =>
                        {
                            b1.Property<int>("ServiceId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("slug");

                            b1.HasKey("ServiceId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_services_slug");

                            b1.ToTable("services");

                            b1.WithOwner()
                                .HasForeignKey("ServiceId");
                        });

                    b.OwnsMany("BOOKLY.Domain.Aggregates.ServiceAggregate.Entities.ServiceSchedule", "ServiceSchedules", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("service_schedule_id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("service_id")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("service_id")
                                .HasDatabaseName("ix_service_schedules_service_id");

                            b1.ToTable("service_schedules", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("service_id");

                            b1.OwnsOne("BOOKLY.Domain.Aggregates.ServiceAggregate.ValueObjects.TimeRange", "Range", b2 =>
                                {
                                    b2.Property<int>("ServiceScheduleId")
                                        .HasColumnType("int");

                                    b2.Property<TimeOnly>("End")
                                        .HasColumnType("time")
                                        .HasColumnName("end_time");

                                    b2.Property<TimeOnly>("Start")
                                        .HasColumnType("time")
                                        .HasColumnName("start_time");

                                    b2.HasKey("ServiceScheduleId");

                                    b2.ToTable("service_schedules");

                                    b2.WithOwner()
                                        .HasForeignKey("ServiceScheduleId");
                                });

                            b1.OwnsOne("BOOKLY.Domain.Aggregates.ServiceAggregate.ValueObjects.Capacity", "Capacity", b2 =>
                                {
                                    b2.Property<int>("ServiceScheduleId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Value")
                                        .HasColumnType("int")
                                        .HasColumnName("capacity");

                                    b2.HasKey("ServiceScheduleId");

                                    b2.ToTable("service_schedules");

                                    b2.WithOwner()
                                        .HasForeignKey("ServiceScheduleId");
                                });

                            b1.OwnsOne("BOOKLY.Domain.Aggregates.ServiceAggregate.ValueObjects.Day", "Day", b2 =>
                                {
                                    b2.Property<int>("ServiceScheduleId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Value")
                                        .HasColumnType("int")
                                        .HasColumnName("day");

                                    b2.HasKey("ServiceScheduleId");

                                    b2.ToTable("service_schedules");

                                    b2.WithOwner()
                                        .HasForeignKey("ServiceScheduleId");
                                });

                            b1.Navigation("Capacity")
                                .IsRequired();

                            b1.Navigation("Day")
                                .IsRequired();

                            b1.Navigation("Range")
                                .IsRequired();
                        });

                    b.OwnsMany("BOOKLY.Domain.Aggregates.ServiceAggregate.Entities.ServiceScheduleUnavailability", "ServiceSchedulesUnavailability", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("service_schedule_unavailability_id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date")
                                .HasColumnName("date");

                            b1.Property<string>("Reason")
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)")
                                .HasColumnName("reason");

                            b1.Property<int>("service_id")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("service_id")
                                .HasDatabaseName("ix_service_schedule_unavailability_service_id");

                            b1.ToTable("service_schedule_unavailability", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("service_id");

                            b1.OwnsOne("BOOKLY.Domain.Aggregates.ServiceAggregate.ValueObjects.TimeRange", "Range", b2 =>
                                {
                                    b2.Property<int>("ServiceScheduleUnavailabilityId")
                                        .HasColumnType("int");

                                    b2.Property<TimeOnly>("End")
                                        .HasColumnType("time")
                                        .HasColumnName("end_time");

                                    b2.Property<TimeOnly>("Start")
                                        .HasColumnType("time")
                                        .HasColumnName("start_time");

                                    b2.HasKey("ServiceScheduleUnavailabilityId");

                                    b2.ToTable("service_schedule_unavailability");

                                    b2.WithOwner()
                                        .HasForeignKey("ServiceScheduleUnavailabilityId");
                                });

                            b1.Navigation("Range");
                        });

                    b.Navigation("DurationMinutes")
                        .IsRequired();

                    b.Navigation("ServiceSchedules");

                    b.Navigation("ServiceSchedulesUnavailability");

                    b.Navigation("Slug")
                        .IsRequired();
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.OwnsOne("BOOKLY.Domain.SharedKernel.Email", "Email", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_users_email");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.AppointmentAggregate.Appointment", b =>
                {
                    b.Navigation("FieldValues");
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.ServiceAggregate.Service", b =>
                {
                    b.Navigation("ServiceSecretaries");
                });
#pragma warning restore 612, 618
        }
    }
}
