// <auto-generated />
using System;
using BOOKLY.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BOOKLY.Infrastructure.Migrations
{
    [DbContext(typeof(BooklyDbContext))]
    [Migration("20260331150716_AddLocationVO")]
    partial class AddLocationVO
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.AppointmentAggregate.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedSecretaryId")
                        .HasColumnType("int")
                        .HasColumnName("assigned_secretary_id");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTime?>("CancelledOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("cancelled_on");

                    b.Property<string>("ClientNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("client_notes");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date_time");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("update_on");

                    b.HasKey("Id");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.AppointmentAggregate.Entities.AppointmentFieldValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("appointment_id");

                    b.Property<int>("FieldDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("field_definition_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("FieldDefinitionId");

                    b.HasIndex("AppointmentId", "FieldDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ux_appointment_field_values_appointment_field");

                    b.ToTable("appointment_field_values", (string)null);
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.AppointmentAggregate.Entities.AppointmentStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("appointment_id");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int")
                        .HasColumnName("new_status");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("occurred_on");

                    b.Property<int?>("OldStatus")
                        .HasColumnType("int")
                        .HasColumnName("old_status");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_appointment_status_history_user_id");

                    b.ToTable("appointment_status_history", (string)null);
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.ServiceAggregate.Entities.ServiceSecretary", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    b.Property<int>("SecretaryId")
                        .HasColumnType("int")
                        .HasColumnName("secretary_id");

                    b.HasKey("ServiceId", "SecretaryId");

                    b.HasIndex("SecretaryId")
                        .HasDatabaseName("ix_service_secretaries_secretary_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_service_secretaries_service_id");

                    b.ToTable("service_secretaries", (string)null);
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.ServiceAggregate.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("Mode")
                        .HasColumnType("int")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int")
                        .HasColumnName("service_type_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_services_owner_id");

                    b.HasIndex("ServiceTypeId")
                        .HasDatabaseName("ix_services_service_type_id");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.ServiceTypeAggregate.Entities.ServiceTypeFieldDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("field_definition_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("FieldType")
                        .HasColumnType("int")
                        .HasColumnName("field_type");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit")
                        .HasColumnName("is_required");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int")
                        .HasColumnName("service_type_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("ServiceTypeId", "SortOrder")
                        .HasDatabaseName("ix_service_type_field_definitions_service_type_sort");

                    b.ToTable("service_type_field_definitions", (string)null);
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.ServiceTypeAggregate.Entities.ServiceTypeFieldOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("field_option_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("FieldDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("field_definition_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("label");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("FieldDefinitionId", "SortOrder")
                        .HasDatabaseName("ix_service_type_field_options_definition_sort");

                    b.HasIndex("FieldDefinitionId", "Value")
                        .IsUnique()
                        .HasDatabaseName("ux_service_type_field_options_definition_value");

                    b.ToTable("service_type_field_options", (string)null);
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.ServiceTypeAggregate.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("service_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_service_types_name");

                    b.ToTable("service_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Consulta médica",
                            IsActive = true,
                            Name = "Consulta"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sesión de tratamiento",
                            IsActive = true,
                            Name = "Tratamiento"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Consulta de seguimiento",
                            IsActive = true,
                            Name = "Seguimiento"
                        });
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.SubscriptionAggregate.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique()
                        .HasDatabaseName("ux_subscriptions_user_id");

                    b.ToTable("subscriptions", null, t =>
                        {
                            t.HasCheckConstraint("ck_subscriptions_free_end_date", "[plan_name] <> 1 OR [end_date] IS NULL");

                            t.HasCheckConstraint("ck_subscriptions_period_dates", "[end_date] IS NULL OR [end_date] >= [start_date]");
                        });
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_users_created_at");

                    b.HasIndex("EmailConfirmed")
                        .HasDatabaseName("ix_users_email_confirmed");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_users_is_active");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.UserAggregate.UserToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_token_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_on");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("purpose");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("used_on");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresOn")
                        .HasDatabaseName("ix_user_tokens_expires_on");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_user_tokens_token_hash");

                    b.HasIndex("UsedOn")
                        .HasDatabaseName("ix_user_tokens_used_on");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_tokens_user_id");

                    b.HasIndex("UserId", "Purpose")
                        .HasDatabaseName("ix_user_tokens_user_id_purpose");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.AppointmentAggregate.Appointment", b =>
                {
                    b.OwnsOne("BOOKLY.Domain.Aggregates.ServiceAggregate.ValueObjects.Duration", "Duration", b1 =>
                        {
                            b1.Property<int>("AppointmentId")
                                .HasColumnType("int");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("duration_minutes");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("appointments");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.OwnsOne("BOOKLY.Domain.Aggregates.AppointmentAggregate.ClientInfo", "Client", b1 =>
                        {
                            b1.Property<int>("AppointmentId")
                                .HasColumnType("int");

                            b1.Property<string>("ClientName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("client_name");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("client_phone");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("appointments");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");

                            b1.OwnsOne("BOOKLY.Domain.SharedKernel.Email", "Email", b2 =>
                                {
                                    b2.Property<int>("ClientInfoAppointmentId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("nvarchar(255)")
                                        .HasColumnName("client_email");

                                    b2.HasKey("ClientInfoAppointmentId");

                                    b2.ToTable("appointments");

                                    b2.WithOwner()
                                        .HasForeignKey("ClientInfoAppointmentId");
                                });

                            b1.Navigation("Email")
                                .IsRequired();
                        });

                    b.Navigation("Client")
                        .IsRequired();

                    b.Navigation("Duration")
                        .IsRequired();
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.AppointmentAggregate.Entities.AppointmentFieldValue", b =>
                {
                    b.HasOne("BOOKLY.Domain.Aggregates.AppointmentAggregate.Appointment", null)
                        .WithMany("FieldValues")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOOKLY.Domain.Aggregates.ServiceTypeAggregate.Entities.ServiceTypeFieldDefinition", null)
                        .WithMany()
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.AppointmentAggregate.Entities.AppointmentStatusHistory", b =>
                {
                    b.HasOne("BOOKLY.Domain.Aggregates.AppointmentAggregate.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOOKLY.Domain.Aggregates.UserAggregate.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.ServiceAggregate.Entities.ServiceSecretary", b =>
                {
                    b.HasOne("BOOKLY.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("SecretaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BOOKLY.Domain.Aggregates.ServiceAggregate.Service", null)
                        .WithMany("ServiceSecretaries")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.ServiceAggregate.Service", b =>
                {
                    b.OwnsOne("BOOKLY.Domain.Aggregates.ServiceAggregate.ValueObjects.Capacity", "Capacity", b1 =>
                        {
                            b1.Property<int>("ServiceId")
                                .HasColumnType("int");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("capacity");

                            b1.HasKey("ServiceId");

                            b1.ToTable("services");

                            b1.WithOwner()
                                .HasForeignKey("ServiceId");
                        });

                    b.OwnsOne("BOOKLY.Domain.Aggregates.ServiceAggregate.ValueObjects.Duration", "DurationMinutes", b1 =>
                        {
                            b1.Property<int>("ServiceId")
                                .HasColumnType("int");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("duration_minutes");

                            b1.HasKey("ServiceId");

                            b1.ToTable("services");

                            b1.WithOwner()
                                .HasForeignKey("ServiceId");
                        });

                    b.OwnsOne("BOOKLY.Domain.Aggregates.ServiceAggregate.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<int>("ServiceId")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)")
                                .HasColumnName("address");

                            b1.Property<string>("GoogleMapsUrl")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("google_maps_url");

                            b1.Property<string>("PlaceName")
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("place_name");

                            b1.HasKey("ServiceId");

                            b1.ToTable("services");

                            b1.WithOwner()
                                .HasForeignKey("ServiceId");
                        });

                    b.OwnsOne("BOOKLY.Domain.Aggregates.ServiceAggregate.ValueObjects.Slug", "Slug", b1 =>
                        {
                            b1.Property<int>("ServiceId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("slug");

                            b1.HasKey("ServiceId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_services_slug");

                            b1.ToTable("services");

                            b1.WithOwner()
                                .HasForeignKey("ServiceId");
                        });

                    b.OwnsMany("BOOKLY.Domain.Aggregates.ServiceAggregate.Entities.ServiceSchedule", "ServiceSchedules", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("service_schedule_id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("service_id")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("service_id")
                                .HasDatabaseName("ix_service_schedules_service_id");

                            b1.ToTable("service_schedules", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("service_id");

                            b1.OwnsOne("BOOKLY.Domain.Aggregates.ServiceAggregate.ValueObjects.Capacity", "Capacity", b2 =>
                                {
                                    b2.Property<int>("ServiceScheduleId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Value")
                                        .HasColumnType("int")
                                        .HasColumnName("capacity");

                                    b2.HasKey("ServiceScheduleId");

                                    b2.ToTable("service_schedules");

                                    b2.WithOwner()
                                        .HasForeignKey("ServiceScheduleId");
                                });

                            b1.OwnsOne("BOOKLY.Domain.Aggregates.ServiceAggregate.ValueObjects.TimeRange", "Range", b2 =>
                                {
                                    b2.Property<int>("ServiceScheduleId")
                                        .HasColumnType("int");

                                    b2.Property<TimeOnly>("End")
                                        .HasColumnType("time")
                                        .HasColumnName("end_time");

                                    b2.Property<TimeOnly>("Start")
                                        .HasColumnType("time")
                                        .HasColumnName("start_time");

                                    b2.HasKey("ServiceScheduleId");

                                    b2.ToTable("service_schedules");

                                    b2.WithOwner()
                                        .HasForeignKey("ServiceScheduleId");
                                });

                            b1.OwnsOne("BOOKLY.Domain.Aggregates.ServiceAggregate.ValueObjects.Day", "Day", b2 =>
                                {
                                    b2.Property<int>("ServiceScheduleId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Value")
                                        .HasColumnType("int")
                                        .HasColumnName("day");

                                    b2.HasKey("ServiceScheduleId");

                                    b2.ToTable("service_schedules");

                                    b2.WithOwner()
                                        .HasForeignKey("ServiceScheduleId");
                                });

                            b1.Navigation("Capacity")
                                .IsRequired();

                            b1.Navigation("Day")
                                .IsRequired();

                            b1.Navigation("Range")
                                .IsRequired();
                        });

                    b.OwnsMany("BOOKLY.Domain.Aggregates.ServiceAggregate.Entities.ServiceUnavailability", "ServicesUnavailability", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("service_unavailability_id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Reason")
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)")
                                .HasColumnName("reason");

                            b1.Property<int>("service_id")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("service_id")
                                .HasDatabaseName("ix_service_unavailabilities_service_id");

                            b1.ToTable("service_unavailabilities", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("service_id");

                            b1.OwnsOne("BOOKLY.Domain.Aggregates.ServiceAggregate.ValueObjects.TimeRange", "TimeRange", b2 =>
                                {
                                    b2.Property<int>("ServiceUnavailabilityId")
                                        .HasColumnType("int");

                                    b2.Property<TimeOnly>("End")
                                        .HasColumnType("time")
                                        .HasColumnName("end_time");

                                    b2.Property<TimeOnly>("Start")
                                        .HasColumnType("time")
                                        .HasColumnName("start_time");

                                    b2.HasKey("ServiceUnavailabilityId");

                                    b2.ToTable("service_unavailabilities");

                                    b2.WithOwner()
                                        .HasForeignKey("ServiceUnavailabilityId");
                                });

                            b1.OwnsOne("BOOKLY.Domain.Aggregates.ServiceAggregate.ValueObjects.DateRange", "DateRange", b2 =>
                                {
                                    b2.Property<int>("ServiceUnavailabilityId")
                                        .HasColumnType("int");

                                    b2.Property<DateOnly>("End")
                                        .HasColumnType("date")
                                        .HasColumnName("end_date");

                                    b2.Property<DateOnly>("Start")
                                        .HasColumnType("date")
                                        .HasColumnName("start_date");

                                    b2.HasKey("ServiceUnavailabilityId");

                                    b2.ToTable("service_unavailabilities");

                                    b2.WithOwner()
                                        .HasForeignKey("ServiceUnavailabilityId");
                                });

                            b1.Navigation("DateRange")
                                .IsRequired();

                            b1.Navigation("TimeRange");
                        });

                    b.Navigation("Capacity")
                        .IsRequired();

                    b.Navigation("DurationMinutes")
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("ServiceSchedules");

                    b.Navigation("ServicesUnavailability");

                    b.Navigation("Slug")
                        .IsRequired();
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.ServiceTypeAggregate.Entities.ServiceTypeFieldDefinition", b =>
                {
                    b.HasOne("BOOKLY.Domain.Aggregates.ServiceTypeAggregate.ServiceType", null)
                        .WithMany("FieldDefinitions")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BOOKLY.Domain.Aggregates.ServiceTypeAggregate.ValueObjects.FieldKey", "Key", b1 =>
                        {
                            b1.Property<int>("ServiceTypeFieldDefinitionId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)")
                                .HasColumnName("key");

                            b1.HasKey("ServiceTypeFieldDefinitionId");

                            b1.ToTable("service_type_field_definitions");

                            b1.WithOwner()
                                .HasForeignKey("ServiceTypeFieldDefinitionId");
                        });

                    b.OwnsOne("BOOKLY.Domain.Aggregates.ServiceTypeAggregate.ValueObjects.FieldLabel", "Label", b1 =>
                        {
                            b1.Property<int>("ServiceTypeFieldDefinitionId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)")
                                .HasColumnName("label");

                            b1.HasKey("ServiceTypeFieldDefinitionId");

                            b1.ToTable("service_type_field_definitions");

                            b1.WithOwner()
                                .HasForeignKey("ServiceTypeFieldDefinitionId");
                        });

                    b.Navigation("Key")
                        .IsRequired();

                    b.Navigation("Label")
                        .IsRequired();
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.ServiceTypeAggregate.Entities.ServiceTypeFieldOption", b =>
                {
                    b.HasOne("BOOKLY.Domain.Aggregates.ServiceTypeAggregate.Entities.ServiceTypeFieldDefinition", null)
                        .WithMany("Options")
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.SubscriptionAggregate.Subscription", b =>
                {
                    b.OwnsOne("BOOKLY.Domain.Aggregates.SubscriptionAggregate.SubscriptionPeriod", "Period", b1 =>
                        {
                            b1.Property<int>("SubscriptionId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("end_date");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("start_date");

                            b1.HasKey("SubscriptionId");

                            b1.ToTable("subscriptions");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");
                        });

                    b.OwnsOne("BOOKLY.Domain.Aggregates.SubscriptionAggregate.SubscriptionPlan", "Plan", b1 =>
                        {
                            b1.Property<int>("SubscriptionId")
                                .HasColumnType("int");

                            b1.Property<int>("MaxSecretaries")
                                .HasColumnType("int")
                                .HasColumnName("max_secretaries");

                            b1.Property<int>("MaxServices")
                                .HasColumnType("int")
                                .HasColumnName("max_services");

                            b1.Property<int>("Name")
                                .HasColumnType("int")
                                .HasColumnName("plan_name");

                            b1.HasKey("SubscriptionId");

                            b1.ToTable("subscriptions");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");
                        });

                    b.Navigation("Period")
                        .IsRequired();

                    b.Navigation("Plan")
                        .IsRequired();
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.OwnsOne("BOOKLY.Domain.Aggregates.UserAggregate.Password", "Password", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("password_hash");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("BOOKLY.Domain.Aggregates.UserAggregate.PersonName", "PersonName", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("last_name");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("BOOKLY.Domain.SharedKernel.Email", "Email", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_users_email");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Password");

                    b.Navigation("PersonName")
                        .IsRequired();
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.UserAggregate.UserToken", b =>
                {
                    b.HasOne("BOOKLY.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.AppointmentAggregate.Appointment", b =>
                {
                    b.Navigation("FieldValues");
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.ServiceAggregate.Service", b =>
                {
                    b.Navigation("ServiceSecretaries");
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.ServiceTypeAggregate.Entities.ServiceTypeFieldDefinition", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("BOOKLY.Domain.Aggregates.ServiceTypeAggregate.ServiceType", b =>
                {
                    b.Navigation("FieldDefinitions");
                });
#pragma warning restore 612, 618
        }
    }
}
